### ISSUE TITLE
Node IRC issue with waartaa in production

### ISSUE THREAD

**Issue by rtnpro** [waartaa/waartaa#101]
Waartaa server is getting restarted because of node-irc throwing an error every now and then. Following is the traceback:

```
/home/waartaa/deploy/current/node_modules/irc/lib/irc.js:632
                    throw err;
                          ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Client.EventEmitter.emit (events.js:74:15)
    at Client.<anonymous> (/home/waartaa/deploy/current/node_modules/irc/lib/irc.js:511:26)
    at Client.EventEmitter.emit (events.js:95:17)
    at /home/waartaa/deploy/current/node_modules/irc/lib/irc.js:629:22
    at Array.forEach (native)
    at CleartextStream.<anonymous> (/home/waartaa/deploy/current/node_modules/irc/lib/irc.js:626:15)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:746:14)
    at CleartextStream.EventEmitter.emit (events.js:92:17)
```

**Comment by rtnpro** [comment]
Fixed by https://github.com/waartaa/node-irc/commit/2585642c8672e63af01cd733030789e542333bc1
