### ISSUE TITLE
Cant see my own messages.

### ISSUE THREAD

**Issue by jayunit100** [waartaa/waartaa#158]
I noticed that when i send a messages, it **doesnt show up in my IRC window**, but the messages is sent just fine.

But I **can** see messages of others.

The funniest part about it, is that it actually **DOES**  appear in the irc window for a breif second, and then it dissapears ?

This might be useful (stack trace printed when i send a message:
```I20140824-16:44:03.181(0)? Exception while invoking method '/channel_logs/insert' TypeError: Cannot call method 'Client' of undefined
I20140824-16:44:03.182(0)?     at _insertInES (app/server/lib/02_irc.js:255:36)
I20140824-16:44:03.182(0)?     at Object.insertInES (app/server/lib/02_irc.js:278:7)
I20140824-16:44:03.183(0)?     at ChannelLogs.allow.insert (app/server/perms.js:18:24)
I20140824-16:44:03.183(0)?     at packages/mongo-livedata/collection.js:784
I20140824-16:44:03.184(0)?     at Array.every (native)
I20140824-16:44:03.184(0)?     at Function._.every._.all (packages/underscore/underscore.js:219)
I20140824-16:44:03.184(0)?     at Meteor.Collection._validatedInsert (packages/mongo-livedata/collection.js:783)
I20140824-16:44:03.185(0)?     at m.(anonymous function) (packages/mongo-livedata/collection.js:704)
I20140824-16:44:03.185(0)?     at maybeAuditArgumentChecks (packages/livedata/livedata_server.js:1487)
I20140824-16:44:03.186(0)?     at packages/livedata/livedata_server.js:643

```
```

**Comment by jayunit100** [comment]
Workaround : Turn off elastic search ( set 'ENABLE_ELASTIC_SEARCH': false,  in the json file)

**Comment by rtnpro** [comment]
Yes! That's correct.
