### ISSUE TITLE
npm install meteorite Failed

### ISSUE THREAD

**Issue by akifkhan** [waartaa/waartaa#56]
npm http GET https://registry.npmjs.org/meteorite

npm ERR! Error: failed to fetch from registry: meteorite
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)

**Comment by LAKnoKAL** [comment]
Try http://stackoverflow.com/questions/21544237/instaling-meteorite

This worked for me
